# Run Identity (Name the task as per the user)
run_identity: "QC_framework_test"

# Data Paths
# This specifies the paths to input data files, including the BAM files, metadata CSV, GFF annotation file, and reference genome FASTA file.
mixed_bams:
  - "../analysis/Test_BAM_files/Mira_4_possorted_genome_bam.bam"
  - "../analysis/Test_BAM_files/possorted_genome_bam.bam"
metadata_csv:
  - "../analysis/cc_barcode_Mira_4.csv"
  - "../analysis/cc_barcode_Mira_1.csv"

gff: "../analysis/jbrowse_env/SM_genes_of_interest.gff3"
genome: "/mnt/data/project0061/bam_manipulation/published/Smansoni_genome/fasta/genome.fa"

# Metadata
sample_id: "LmexAmpB"

# CSV Column Names
# This section defines the expected column names in the metadata CSV file. The user can customize these if their CSV uses different column names for barcodes, cell types, or BAM file associations.
csv_columns:
  barcode: "cell_barcode"
  cell_type: "Cluster"
  bam_file: "bam_file"  # Optional column to specify which BAM file each barcode belongs to

# Sequencing Parameters
read_mode: "single"   # Options: "single" or "paired"
fragment_length: 200  # Average length of your RNA fragments(350)
fragment_sd: 20       # Standard deviation of fragment length(60)

# Optional parameter
# This classifies unassigned (IC:i:0) reads into "scored but below threshold" vs "never pseudo-aligned"
run_ic0_profiling: true  # To run make it as true if not keep it as false