---
title: "easy_check_miracidia"
author: "F Blow"
date: "2024-12-12"
output: html_document
---
  
```{r}
# function to check install and load packages
load_library <- function(pkg) {
  # check if package is installed
  new_package <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  
  # install any new packages
  if (length(new_package)) 
    install.packages(new_package, dependencies = TRUE, Ncpus = 6)
  
  # sapply to loop through and load packages
  invisible(sapply(pkg, library, character.only = TRUE))
  
  # give message confirming load
  message("The following packages are now loaded")
  print(names(sessionInfo()$otherPkgs))
}
```

```{r}
packages <- c('tidyverse', 'Seurat', 'RColorBrewer', 'patchwork','ggpubr')
load_library(packages)
```

```{r}
run1.combined.v10 <- readRDS(file = "run1.combined.v10_integrated_55.rds")
```

```{r}
DimPlot(run1.combined.v10, reduction = "umap", label = TRUE, repel = TRUE)
```

```{r}
DefaultAssay(run1.combined.v10) <- "integrated"
run1.combined.v10 <- RenameIdents(object = run1.combined.v10, 
                               "0" = "Muscle 1",
                               "1" = "Stem C",
                               "2" = "Stem D",
                               "3" = "Stem F",
                               "4" = "Stem A",
                               "5" = "Stem B",
                               "6" = "Neuron 1",
                               "7" = "Muscle 2",
                               "8" = "Neuron 4",
                               "9" = "Parenchyma 1",
                               "10" = "Stem E",
                               "11" = "Parenchyma 2",
                               "12" = "Protonephridia",
                               "13" = "Tegument",
                               "14" = "Neuron 2",
                               "15" = "Neuron 5",
                               "16" = "Stem G",
                               "17" = "Ciliary plate", 
                              "18" = "Neuron 3")


run1.combined.v10[["merge.ident"]] <- Idents(object = run1.combined.v10)
run1.combined.v10[["may.ident"]] <- Idents(object = run1.combined.v10)

DimPlot(run1.combined.v10, reduction = "umap", label=TRUE) #visulaises the UMAP
p2 <- DimPlot(run1.combined.v10, reduction = "umap", label = TRUE, repel = TRUE)
p2
```
```{r}
new_pal <- c("#9E0059","#007aaa","#ffb703","#B3E9C7","#fb8500","#7851a9","#00325b","#8ACB88","#107E7D", "#FB6376", "#c40c18", "#FFFD82", "#2191FB", "#690500", "#57467B", "#B57F50","#2C514C","#c4b7cb" ,"#FFCDB2" )
scales::show_col(new_pal)
plot1 <- DimPlot(run1.combined.v10, reduction = "umap", label = FALSE, repel = TRUE, label.box = FALSE) + NoLegend() +scale_color_manual(values = new_pal)
LabelClusters(plot1, id = "ident", color = 'black', size =4, repel = T,  box.padding = 1.75)
```

## Check the expression of genes of interest
```{r}
DefaultAssay(run1.combined.v10) <- "RNA"
plot1 <- FeaturePlot(run1.combined.v10, features = "Smp-068240")
LabelClusters(plot1, id = "ident", color = 'black', size =4, repel = T,  box.padding = 1.75, max.overlaps = Inf)
```

```{r}
idents_df <- data.frame(
  Cell = names(Idents(run1.combined.v10)),
  Cluster = as.character(Idents(run1.combined.v10))
)
```

```{r}

write.csv(idents_df, "cc_barcode.csv", row.names = FALSE)
```




